### ISSUE TITLE
The footer is not aligned to the bottom

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#355]
**Describe the bug**
- In some views, the footer is not aligned to the bottom of the screen.

**To Reproduce**
1. Go to a view with a footer
2. Scroll down to the footer
3. See error

**Expected behavior**
- Footer needs to be aligned to the bottom

**Screenshots**
<img width="904" alt="Screenshot 2022-07-30 at 8 03 16 PM" src="https://user-images.githubusercontent.com/43912578/181919062-ad9b7a69-247c-42bc-bfe6-5d4dfb670015.png">

**Comment by YoshithaRathnayake** [comment]
Will I able to do this @anjula-sack ?, If I abe can I work on this?

**Comment by Madhawa97** [comment]
Hey guys. I tried working on this but faced some issues when setting up the project locally. can somebody assist me?

**Comment by Madhawa97** [comment]
@anjula-sack I visited all the routes listed on the `src/index.tes` but couldn't reproduce the [issue](https://github.com/sef-global/scholarx-frontend/issues/355). can you let me know where should I look at?  

And which numbers should I use instead of the  `:programId`  when visiting these routes?

<img width="1331" alt="Screenshot 2022-08-08 at 22 00 08" src="https://user-images.githubusercontent.com/70215958/183467412-bc86f1ee-9f3d-4fa3-b12e-4832cc130cf9.png">
